"""creacion de tablas del consultorio

Revision ID: 45e2118fe6ee
Revises: 
Create Date: 2026-10-08 22:34:36.897285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e2118fe6ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odontologos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellidos', sa.Text(), nullable=False),
    sa.Column('cop', sa.VARCHAR(length=10), nullable=False),
    sa.Column('especialidad', sa.Text(), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cop')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellidos', sa.Text(), nullable=False),
    sa.Column('dni', sa.VARCHAR(length=8), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=15), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'ATENDIDA', 'CANCELADA', name='estadocita'), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('odontologo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['odontologo_id'], ['odontologos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('odontologos')
    # En PostgreSQL el ENUM es un tipo aparte y hay que eliminarlo manualmente
    sa.Enum(name='estadocita').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
